### ISSUE TITLE
Preset conditions

### ISSUE THREAD

**Issue by Don-Li** [Don-Li/CABexpt#3]
Set something up such that the parameters of an experiment can be set in advance for some given number of sessions. Perhaps an expt_setup.py file that generates a bash script that runs the experiment with the desired parameters.

**Comment by stefelisabeth** [comment]
Sounds good. As soon as I finish my manuscript tomorrow!

**Comment by Don-Li** [comment]
Have a look at this
[x.txt](https://github.com/Don-Li/CABexpt/files/1117488/x.txt)
[test1.txt](https://github.com/Don-Li/CABexpt/files/1117489/test1.txt)
